-- MySQL Script generated by MySQL Workbench
-- Fri May 26 10:36:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Academia_Gontijo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Academia_Gontijo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Academia_Gontijo` DEFAULT CHARACTER SET utf8 ;
USE `Academia_Gontijo` ;

-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`Treinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`Treinadores` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`Treinadores` (
  `trei_id` INT NOT NULL AUTO_INCREMENT,
  `trei_nome` VARCHAR(100) NOT NULL,
  `trei_sexo` ENUM('M', 'F') NOT NULL,
  PRIMARY KEY (`trei_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`Atletas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`Atletas` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`Atletas` (
  `atle_id` INT NOT NULL AUTO_INCREMENT,
  `atle_nome` VARCHAR(100) NOT NULL,
  `atle_cpf` VARCHAR(11) NOT NULL,
  `atle_dt_nasc` DATE NOT NULL,
  `atle_sexo` ENUM('M', 'F') NOT NULL,
  `atle_peso` FLOAT NOT NULL,
  `atle_altura` FLOAT NOT NULL,
  `atle_obs` VARCHAR(300) NOT NULL,
  `atle_trei_id` INT NOT NULL,
  PRIMARY KEY (`atle_id`),
  INDEX `fk_Atletas_Treinadores_idx` (`atle_trei_id` ASC),
  CONSTRAINT `fk_Atletas_Treinadores`
    FOREIGN KEY (`atle_trei_id`)
    REFERENCES `Academia_Gontijo`.`Treinadores` (`trei_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`TiposDeTreinos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`TiposDeTreinos` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`TiposDeTreinos` (
  `tptr_id` INT NOT NULL AUTO_INCREMENT,
  `tptr_nome` VARCHAR(45) NOT NULL,
  `tptr_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tptr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`Exercicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`Exercicios` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`Exercicios` (
  `exer_id` INT NOT NULL AUTO_INCREMENT,
  `exer_nome` VARCHAR(50) NOT NULL,
  `exer_descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`exer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`Treinos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`Treinos` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`Treinos` (
  `trei_atle_id` INT NOT NULL,
  `trei_exer_id` INT NOT NULL,
  `trei_sequencia` INT NOT NULL,
  `trei_pretencao` VARCHAR(50) NOT NULL,
  `trei_repeticoes` INT NULL,
  `trei_series` INT NULL,
  `trei_tempo` INT NULL,
  INDEX `fk_Exercicios_has_Atletas_Atletas1_idx` (`trei_exer_id` ASC),
  INDEX `fk_Exercicios_has_Atletas_Exercicios1_idx` (`trei_atle_id` ASC),
  PRIMARY KEY (`trei_atle_id`, `trei_exer_id`, `trei_sequencia`),
  CONSTRAINT `fk_Exercicios_has_Atletas_Exercicios1`
    FOREIGN KEY (`trei_atle_id`)
    REFERENCES `Academia_Gontijo`.`Exercicios` (`exer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exercicios_has_Atletas_Atletas1`
    FOREIGN KEY (`trei_exer_id`)
    REFERENCES `Academia_Gontijo`.`Atletas` (`atle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia_Gontijo`.`Treinamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Academia_Gontijo`.`Treinamentos` ;

CREATE TABLE IF NOT EXISTS `Academia_Gontijo`.`Treinamentos` (
  `trem_trei_atle_id` INT NOT NULL,
  `trem_trei_exer_id` INT NOT NULL,
  `trem_trei_sequencia` INT NOT NULL,
  `trem_tptr_id` INT NOT NULL,
  PRIMARY KEY (`trem_trei_atle_id`, `trem_trei_exer_id`, `trem_trei_sequencia`, `trem_tptr_id`),
  INDEX `fk_Treinos_has_TiposDeTreinos_TiposDeTreinos1_idx` (`trem_tptr_id` ASC),
  INDEX `fk_Treinos_has_TiposDeTreinos_Treinos1_idx` (`trem_trei_atle_id` ASC, `trem_trei_exer_id` ASC, `trem_trei_sequencia` ASC),
  CONSTRAINT `fk_Treinos_has_TiposDeTreinos_Treinos1`
    FOREIGN KEY (`trem_trei_atle_id` , `trem_trei_exer_id` , `trem_trei_sequencia`)
    REFERENCES `Academia_Gontijo`.`Treinos` (`trei_atle_id` , `trei_exer_id` , `trei_sequencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treinos_has_TiposDeTreinos_TiposDeTreinos1`
    FOREIGN KEY (`trem_tptr_id`)
    REFERENCES `Academia_Gontijo`.`TiposDeTreinos` (`tptr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
